-- 01_setup.sql
USE ROLE TRAINING_ROLE;
USE WAREHOUSE COMPUTE_WH;

-- Use project DB
USE DATABASE REVIEWSENSE_DB;

-- Create schemas
CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS CURATED;

-- Create file format + stage
USE SCHEMA RAW;

CREATE OR REPLACE FILE FORMAT PARQUET_FF TYPE = PARQUET;

CREATE OR REPLACE STAGE ELECTRONICS_STAGE
  FILE_FORMAT = PARQUET_FF;

-- Quick check
SHOW STAGES LIKE 'ELECTRONICS_STAGE' IN SCHEMA RAW;