USE ROLE TRAINING_ROLE;

USE WAREHOUSE COMPUTE_WH;

USE DATABASE REVIEWSENSE_DB;
 
USE SCHEMA RAW;

SHOW TABLES;
 
USE SCHEMA CURATED;

SHOW TABLES;
 
SELECT COUNT(*) FROM RAW.ELECTRONICS_REVIEWS_RAW;

SELECT COUNT(*) FROM CURATED.ELECTRONICS_REVIEWS;



-- 1) 看 RAW 表有多少行（给它起别名，避免混淆）
SELECT COUNT(*) AS raw_cnt
FROM RAW.ELECTRONICS_REVIEWS_RAW;

-- 2) 看 CURATED 表有多少行
SELECT COUNT(*) AS curated_cnt
FROM CURATED.ELECTRONICS_REVIEWS;

-- 3) 抽样看一条 RAW 的结构（确认是不是 VARIANT v）
SELECT *
FROM RAW.ELECTRONICS_REVIEWS_RAW
LIMIT 3;

-- 4) 抽样看一条 CURATED 的结构（确认字段已解析）
SELECT review_id, asin, user_id, rating, title, review_text, review_ts
FROM CURATED.ELECTRONICS_REVIEWS
LIMIT 10;



SELECT 'RAW' AS layer, COUNT(*) AS cnt
FROM RAW.ELECTRONICS_REVIEWS_RAW
UNION ALL
SELECT 'CURATED', COUNT(*)
FROM CURATED.ELECTRONICS_REVIEWS;

SELECT
  COUNT(*) AS total,

  SUM(IFF(review_id IS NULL, 1, 0)) AS null_review_id,
  SUM(IFF(asin IS NULL, 1, 0)) AS null_asin,
  SUM(IFF(rating IS NULL, 1, 0)) AS null_rating,
  SUM(IFF(review_text IS NULL, 1, 0)) AS null_review_text,
  SUM(IFF(review_ts IS NULL, 1, 0)) AS null_review_ts

FROM CURATED.ELECTRONICS_REVIEWS;


SELECT rating, COUNT(*) AS cnt
FROM CURATED.ELECTRONICS_REVIEWS
GROUP BY rating
ORDER BY rating;

SELECT COUNT(*) AS negative_cnt
FROM CURATED.ELECTRONICS_REVIEWS
WHERE rating <= 2;

SELECT verified_purchase, COUNT(*) AS cnt
FROM CURATED.ELECTRONICS_REVIEWS
GROUP BY verified_purchase
ORDER BY cnt DESC;


SELECT
  review_id,
  helpful_vote,
  rating,
  LEFT(review_text, 120) AS preview
FROM CURATED.ELECTRONICS_REVIEWS
ORDER BY helpful_vote DESC NULLS LAST
LIMIT 10;


SELECT GET_DDL('TABLE', 'RAW.ELECTRONICS_REVIEWS_RAW');



