USE ROLE TRAINING_ROLE;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE REVIEWSENSE_DB;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE CORTEX SEARCH SERVICE REVIEW_SEARCH
    ON REVIEW_TEXT_CLEAN
    ATTRIBUTES ASIN, RATING, VERIFIED_PURCHASE, HELPFUL_VOTE, REVIEW_TS
    WAREHOUSE = COMPUTE_WH
    TARGET_LAG = '1 hour'
AS
    SELECT
        REVIEW_ID,
        ASIN,
        RATING,
        VERIFIED_PURCHASE,
        HELPFUL_VOTE,
        REVIEW_TS,
        REVIEW_TEXT_CLEAN
    FROM REVIEWSENSE_DB.ANALYTICS.REVIEWS_CLEAN_FOR_EMBEDDINGS;