USE ROLE TRAINING_ROLE;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE REVIEWSENSE_DB;

SELECT CURRENT_DATABASE(), CURRENT_SCHEMA(), CURRENT_ROLE(), CURRENT_WAREHOUSE();

SHOW TABLES IN SCHEMA REVIEWSENSE_DB.CURATED;

DESC TABLE REVIEWSENSE_DB.CURATED.ELECTRONICS_REVIEWS;

CREATE SCHEMA IF NOT EXISTS REVIEWSENSE_DB.ANALYTICS;

CREATE OR REPLACE VIEW REVIEWSENSE_DB.ANALYTICS.V_REVIEWS_GENAI_BASE AS
SELECT
  REVIEW_ID::STRING           AS REVIEW_ID,
  ASIN::STRING                AS ASIN,
  USER_ID::STRING             AS USER_ID,
  RATING::NUMBER              AS RATING,
  TITLE::STRING               AS TITLE,
  REVIEW_TEXT::STRING         AS REVIEW_TEXT,
  VERIFIED_PURCHASE::BOOLEAN  AS VERIFIED_PURCHASE,
  HELPFUL_VOTE::NUMBER        AS HELPFUL_VOTE,
  REVIEW_TS::TIMESTAMP_NTZ    AS REVIEW_TS,
  CATEGORY::STRING            AS CATEGORY
FROM REVIEWSENSE_DB.CURATED.ELECTRONICS_REVIEWS;

USE WAREHOUSE COMPUTE_WH;

SELECT
  REVIEW_ID,
  ASIN,
  RATING,
  VERIFIED_PURCHASE,
  HELPFUL_VOTE,
  LEFT(REVIEW_TEXT, 120) AS PREVIEW,
  REVIEW_TS,
  CATEGORY
FROM REVIEWSENSE_DB.ANALYTICS.V_REVIEWS_GENAI_BASE
LIMIT 10;

CREATE OR REPLACE TABLE REVIEWSENSE_DB.ANALYTICS.REVIEWS_FOR_GENAI AS
SELECT
  REVIEW_ID,
  ASIN,
  USER_ID,
  RATING,
  TITLE,
  REVIEW_TEXT,
  VERIFIED_PURCHASE,
  HELPFUL_VOTE,
  REVIEW_TS,
  CATEGORY,
  LENGTH(TRIM(REVIEW_TEXT)) AS TEXT_LEN
FROM REVIEWSENSE_DB.ANALYTICS.V_REVIEWS_GENAI_BASE
WHERE REVIEW_TEXT IS NOT NULL
  AND LENGTH(TRIM(REVIEW_TEXT)) >= 20
  AND RATING BETWEEN 1 AND 5
  AND REVIEW_TS IS NOT NULL;

  SELECT COUNT(*) FROM REVIEWSENSE_DB.ANALYTICS.REVIEWS_FOR_GENAI;

  SELECT COUNT(*) FROM REVIEWSENSE_DB.CURATED.ELECTRONICS_REVIEWS;




-- 1) 新的，基于上周过滤后的版本
USE ROLE TRAINING_ROLE;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE REVIEWSENSE_DB;

SELECT COUNT(*) AS curated_cnt
FROM CURATED.ELECTRONICS_REVIEWS;

SELECT COUNT(*) AS dedup_cnt
FROM CURATED.V_ELECTRONICS_REVIEWS_DEDUP;

CREATE SCHEMA IF NOT EXISTS REVIEWSENSE_DB.ANALYTICS;

CREATE OR REPLACE VIEW REVIEWSENSE_DB.ANALYTICS.V_REVIEWS_GENAI_BASE AS
SELECT
  REVIEW_ID::STRING           AS REVIEW_ID,
  ASIN::STRING                AS ASIN,
  USER_ID::STRING             AS USER_ID,
  RATING::NUMBER              AS RATING,
  TITLE::STRING               AS TITLE,
  REVIEW_TEXT::STRING         AS REVIEW_TEXT,
  VERIFIED_PURCHASE::BOOLEAN  AS VERIFIED_PURCHASE,
  HELPFUL_VOTE::NUMBER        AS HELPFUL_VOTE,
  REVIEW_TS::TIMESTAMP_NTZ    AS REVIEW_TS,
  CATEGORY::STRING            AS CATEGORY
FROM REVIEWSENSE_DB.CURATED.V_ELECTRONICS_REVIEWS_DEDUP;

CREATE OR REPLACE TABLE REVIEWSENSE_DB.ANALYTICS.REVIEWS_FOR_GENAI AS
SELECT
  REVIEW_ID,
  ASIN,
  USER_ID,
  RATING,
  TITLE,
  REVIEW_TEXT,
  VERIFIED_PURCHASE,
  HELPFUL_VOTE,
  REVIEW_TS,
  CATEGORY,
  LENGTH(TRIM(REVIEW_TEXT)) AS TEXT_LEN
FROM REVIEWSENSE_DB.ANALYTICS.V_REVIEWS_GENAI_BASE
WHERE REVIEW_TEXT IS NOT NULL
  AND LENGTH(TRIM(REVIEW_TEXT)) >= 20
  AND RATING BETWEEN 1 AND 5
  AND REVIEW_TS IS NOT NULL;

  SELECT
  (SELECT COUNT(*) FROM CURATED.ELECTRONICS_REVIEWS) AS curated_total,
  (SELECT COUNT(*) FROM CURATED.V_ELECTRONICS_REVIEWS_DEDUP) AS dedup_total,
  (SELECT COUNT(*) FROM ANALYTICS.REVIEWS_FOR_GENAI) AS genai_ready_total;

  SELECT
  COUNT(*) AS total,
  ROUND(AVG(TEXT_LEN), 2) AS avg_text_len,
  MIN(TEXT_LEN) AS min_text_len,
  MAX(TEXT_LEN) AS max_text_len
FROM REVIEWSENSE_DB.ANALYTICS.REVIEWS_FOR_GENAI;